### ISSUE TITLE
errors with webpack

### ISSUE THREAD

**Issue by Jan-Jan** [microapps/shopify-api-node#88]
Sorry to bother: 

I get two errors when using nodify-shopify with webpack

```
ERROR in ./~/nodify-shopify/index.js
Module not found: Error: Cannot resolve module 'fs' in /Users/naturgewalt/Coding/gigster/vavavoo-slingshot/node_modules/nodify-shopify
 @ ./~/nodify-shopify/index.js 6:11-24
```

```
ERROR in ./~/nodify-shopify/package.json
Module parse failed: ./node_modules/nodify-shopify/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "nodify-shopify",
|   "version": "0.2.1",
|   "description": "Shopify API client",
 @ ./~/nodify-shopify/index.js 8:12-32

ERROR in ./~/nodify-shopify/~/got/package.json
Module parse failed: ./node_modules/nodify-shopify/node_modules/got/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "got",
|   "version": "6.2.0",
|   "description": "Simplified HTTP/HTTPS requests",
 @ ./~/nodify-shopify/~/got/index.js 21:12-37
```

I can make the latter go away by adding to webpack.conf
```
loaders: [{ test: /\.json$/, loader: "json-loader" }]
```
but no other package requires this...

The primary I can make the parse error go away using
```
target: 'node'
```
but, then I get a failure
```
Uncaught ReferenceError: require is not defined
```
(which is understandable since I not compiling for the web)

**Comment by lpinca** [comment]
This is a bit problematic.

The first issue is [`fs.readdirSync`](https://github.com/microapps/Nodify-Shopify/blob/dc7cdc7f4c30d532902aa3119aeea6c7492eadf7/index.js#L79). I'm not familiar with webpack but with browserify you can use the `brfs` transform and get the list of resources as expected in the bundle. I guess the same can be achieved in webpack.

The second issue is that resources are [required and instantiated lazily](https://github.com/microapps/Nodify-Shopify/blob/dc7cdc7f4c30d532902aa3119aeea6c7492eadf7/index.js#L80-L93). This will not work with bundlers because AFAIK they can only read `require()` calls that are statically analyzable.

So I think that right now there is no way to use the lib in the browser unless we remove the lazy require feature.

**Comment by lpinca** [comment]
Actually it seems that webpack supports dynamic requires. I'll see if I can find a way to make it work.

**Comment by lpinca** [comment]
I managed to make it work with webpack. Here is the configuration and the required dependencies:

```js
'use strict';

module.exports = {
  entry: './index.js',
  output: {
    filename: 'bundle.js',
    libraryTarget: 'umd',
    library: 'Shopify'
  },
  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.js$/,
        loader: 'transform?brfs'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015']
        }
      }
    ]
  }
};
```

```
babel-loader
babel-preset-es2015
brfs
json-loader
transform-loader
webpack
```

It seems to work but the generated bundle is ~750 KB :smile: (~180 KB when minimized).
As said above, I'm not a webpack expert so maybe it can be improved.

**Comment by lpinca** [comment]
With 5f83632f8efa0cb7abf213ec95ba49dc097f3a04 the size of the generated bundle is ~380 KB (~130 KB minimized). We can reduce it further by removing the `lodash` dependency and using some lightweight alternatives for `_.pick` and `_.omit`, but I don't know if it makes sense as the library has not been designed for the browser.

**Comment by Jan-Jan** [comment]
Thanks for this!
