### ISSUE TITLE
Error: writing metafield data as part of product of variant

### ISSUE THREAD

**Issue by Jan-Jan** [microapps/shopify-api-node#89]
Me again, sorry.

I'm trying to include metafield data when writing to a product (or variant).

When I create/update a product I simply include as part of the object { "variants": [{...}, {...}] } and everything works great. While I get successful save messages it has no effect if I include { "metafield": {...} } or { "metafields": [{...}, {...}] }.

Is this by design? What is the best practice for working with metafields?

**Comment by lpinca** [comment]
Hi,
according to the [documentation](https://docs.shopify.com/api/reference/product#update) the format of your second example is correct:
```js
{ 
  metafields: [{ }] 
}
```
but if you look at the response, the list of metafields is not included.

After you've added the metafield/s try to see if you can retrieve it in this way:
```js
shopify.metafield.list({
  metafield: {
    owner_resource: 'product',
    owner_id: 1234
  }
});
```

**Comment by Jan-Jan** [comment]
If I try
```
shopify.product.update(1234, {
  metafields: [{  }],
  id: 1234,
});
```
gives the following error ```API ERROR:   HTTPError: Response code 422 (Unprocessable Entity)```
However, I can add metafields to a variant, ie, I can update the following without getting an error:
```
shopify.product.update(1234, {
  id: 1234,
  variants: [{
    metafields: [{  }],
  }],
});
```
But, then when I query ```shopify.metafield.list();``` nothing has been saved.

**Comment by lpinca** [comment]
It probably gives you a `422` error because the metafield is invalid.
Does the same happens if you use the same example in the api documentation? e.g.:

```js
shopify.product.update(1234, {
  metafields: [{
    key: 'new',
    value: 'newvalue',
    value_type: 'string',
    namespace: 'global'
  }],
  id: 1234,
});
```

where `1234` is obviously an existing id for a product.

`shopify.metafield.list()` returns the metafields of the shop and this is probably why your list is empty. To get the metafields of a resource you should use this filter (I'm not sure if it actually works):

```js
shopify.metafield.list({
  metafield: {
    owner_resource: 'product',
    owner_id: 1234
  }
});
```

Let me know if at least the `422` error is fixed in this way.

**Comment by Jan-Jan** [comment]
Thank you that clears things up. I used my own namespace, and that appeared to give problems (sometimes)...

How do i get ```shopify.product.list()``` to include meta-fields in the result?

**Comment by Jan-Jan** [comment]
I found the update error (I think). I was writing to metafields an entry with an existing key & namespace combination, without including the id.

**Comment by lpinca** [comment]
> How do i get `shopify.product.list()` to include meta-fields in the result?

Unfortunately you can't with a single request. First you have to get the product list, then map for each product its metafields using `shopify.metafield.list` as shown above.

**Comment by lpinca** [comment]
Something like this (simplified for a single product):
```js
shopify.product.get(1234)
.then(product => {
  return shopify.metafield.list({
    metafield: {
      owner_resource: 'product',
      owner_id: product.id
    }
  })
  .then(metafields => {
    product.metafields = metafields;
    return product;
  })
})
.then(product => console.log(product));
```
P.S. I haven't tested the above code.

**Comment by Jan-Jan** [comment]
Thanks Ipinca. I need this for lists of products, but I will create a work around.

**Comment by Jan-Jan** [comment]
PS. Thanks for all the help.

**Comment by BarryCarlyon** [comment]
To chip in, I found that a product update with meta fields will work if the meta field didn't exist.

If the metafield exists you get a 422.

So do product update or create to add the meta field to the product initially.

THEN you use the metafields update to update the metafield (instead of passing metafields in the product update)
